### ISSUE TITLE
deps 

### ISSUE THREAD

**Issue by huahaiy** [joinr/datalevinbench#1]
The deps on LMDBJava needs to be change back to 0.8.1 for this to run. 0.9.24-1 is for the LMDBJava-native, which is already included in LMDBJava.

**Comment by joinr** [comment]
Apologies, I didn't realize I'd committed that change.  Also very strange; I though I had run it successfully, maybe too much coffee.
I will leave the configuration alone so it's stable for anyone else cloning and running.

fixed in 3da7184
